### ISSUE TITLE
about access network share file

### ISSUE THREAD

**Issue by wangsongtaoliuli** [slavaim/MacOSX-VFS-Isolation-Filter#1]
I am trying to access files on the local machine or remote machine through network share. When I access(read or write) file on the local machine, it works well. The operation of lookup or create will replace the original vnode (covered vnode)with the new vnode(covering vnode). When the operation of read or write comes, the input parameters is the new vnode. But when I access files on remote machine through network share. The input parameters of read or write operations is original vnode, although I replace the original vnode (covered vnode)with the new vnode(covering vnode). Are there some difference between access files on local machine and remote network share machine.

an early reply would be appreciated
Best regards

**Comment by slavaim** [comment]
An original vnode can be returned by the name cache. You could consider purging the name cache from FltHookVnodeVop by calling cache_purge for the VDIR type vnodes. Also the github version has an incomplete hooks implementation by ignoring vfsops operations vector which contains the vfs_vget operation that can be used to lookup vnode by id. 
There is a special case if you are filtering on the per-process basis. In this case purging the cache is not enough and some measures are required to bypass the name cache for a particular process. This code is not present in the github version.

**Comment by wangsongtaoliuli** [comment]
Hi Slava,
I tried to skip name cache by calling cache_purge, but it does not work. When I access network share files on the remote machine using process nano,  the lookup function is called, and replace the covered vnode with the covering vnode. But when nano read or write , the readhook and writehook  function still  receive the original vnode. so nano still get the original vnode but not the covering vnode.

If the original vnode is get from name cache, the lookup hook should not be called, so I think in this case the original vnode is not get from namecache, I think after calling VNOP_LOOKUP, maybe kernel update the vnode, I am not sure.

The logs are below:
2018.11.2 11:4:54 196152.VifVnodeHashTable::CreateAndAddIOVnodByBSDVnode, the ioVnodeNew:0x25a6f000, vnode: 0x21d0f2e8, dldVnodeType:0.
2018.11.2 11:4:54 196156.FltHookVnodeVop return 3, vnode=0x21d0f2e8.
2018.11.2 11:4:54 196158.VifFsdLookupHook dldVnode is 0x25a6f000, vnode:0x21d0f2e8,dldvnode type:0, filename:/Volumes/mac/Users/mac/wst/share/test1234.txt, procname:Finder
2018.11.2 11:4:54 196240.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:4:54 196247.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:4:54 204998.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:4:54 205007.VifFsdGetattrHook vnode:0x21d0f2e8.
**2018.11.2 11:6:37 817992.VifFsdLookupHook dldVnode is 0x25a6f000, vnode:0x21d0f2e8,dldvnode type:0, filename:/Volumes/mac/Users/mac/wst/share/test1234.txt, procname:nano**
**2018.11.2 11:6:37 818011.VifFsdLookupHook This is the old vnode,0x21d0f2e8**
**2018.11.2 11:6:37 818013.VifReplaceVnodeByCovering dldVnode type is 0.dldVnodeis 0x25a6f000, vnode is 0x21d0f2e8**
2018.11.2 11:6:37 818084.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:6:37 818095.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:6:37 818104.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:6:37 818652.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:6:37 824358.VifFsdLookupHook dldVnode is 0x25a6f000, vnode:0x21d0f2e8,dldvnode type:0, filename:/Volumes/mac/Users/mac/wst/share/test1234.txt, procname:nano
2018.11.2 11:6:37 824375.VifFsdLookupHook This is the old vnode,0x21d0f2e8
2018.11.2 11:6:37 824377.VifReplaceVnodeByCovering dldVnode type is 0.dldVnodeis 0x25a6f000, vnode is 0x21d0f2e8
2018.11.2 11:6:37 824384.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:6:37 824394.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:6:37 824397.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:6:37 826578.VifFsdGetattrHook vnode:0x21d0f2e8.
2018.11.2 11:6:37 826585.Enter the function of VnodeAuthorizeCallback, vnode = 0x21d0f2e8.filename:test1234.txt
2018.11.2 11:6:37 826588.FltHookVnodeVop return 3, vnode=0x21d0f2e8.
2018.11.2 11:6:37 827006.VifFsdGetattrHook vnode:0x21d0f2e8.
**2018.11.2 11:6:37 827018.VifFsdReadHook  filename:test1234.txt  procname:nano oriVnode:0x21d0f2e8, vnode:0x21d0f2e8.
2018.11.2 11:6:37 827637.VifFsdReadHook  filename:test1234.txt  procname:nano oriVnode:0x21d0f2e8, vnode:0x21d0f2e8.**


an early reply would be appreciated
Best regards

**Comment by slavaim** [comment]
As I do not know the code modifications you made I suggest to
 - call cache_purge(ap->a_dvp) from the lookup hook before returning
 - set a break point to (*ap->a_vpp)->v_mount->mnt_op->vfs_vget . Should it be invoked and return an original vnode you need to implement a hook for it.
 - verify before returning from a lookup hook that *ap->a_vpp does contain a covering vnode

**Comment by slavaim** [comment]
In addition I would check whether the problem persists only for files opened from the root of the mounted shared folder if /Volumes/mac/Users/mac/wst/share is a mount point, i.e /Volumes/mac/Users/mac/wst/share/file.txt vs /Volumes/mac/Users/mac/wst/share/a/b/c/file.txt

**Comment by wangsongtaoliuli** [comment]
Thank you for your replay.
I have checked the problem persists in both the root of the mounted shared folder and  sub shared folder.
I hooked the vfs_vget function and log the returned vnode . It seems like the vnode returned from vfs_vget function. 
The log information as following: 
**2018.11.6 18:14:0 651043.VifVfsMntHook::VifVfsVGetHook vnode:0x16f09930 error:0.**
2018.11.6 18:14:0 660332.VifFsdLookupHook dldVnode is 0x16fc1180, vnode:0x16f09930,dldvnode type:0, filename:/Volumes/mac/Users/mac/wst/share/test1234.txt, procname:Finder
2018.11.6 18:14:0 660346.VifFsdGetattrHook vnode:0x16f09930.
2018.11.6 18:14:0 660351.Enter the function of VnodeAuthorizeCallback, vnode = 0x16f09930.filename:test1234.txt
2018.11.6 18:14:0 660353.FltHookVnodeVop return 3, vnode=0x16f09930.
2018.11.6 18:14:0 660356.VifFsdGetattrHook vnode:0x16f09930.
2018.11.6 18:14:0 660359.VifFsdGetattrHook vnode:0x16f09930.
2018.11.6 18:14:0 661920.VifFsdLookupHook dldVnode is 0x16fc1180, vnode:0x16f09930,dldvnode type:0, filename:/Volumes/mac/Users/mac/wst/share/test1234.txt, procname:Finder
2018.11.6 18:14:0 661933.VifFsdGetattrHook vnode:0x16f09930.
2018.11.6 18:14:2 771916.VifFsdLookupHook dldVnode is 0x16fc1180, vnode:0x16f09930,dldvnode type:0, filename:/Volumes/mac/Users/mac/wst/share/test1234.txt, procname:nano
2018.11.6 18:14:2 771932.VifFsdLookupHook This is the old vnode,0x16f09930
2018.11.6 18:14:2 771934.VifReplaceVnodeByCovering dldVnode type is 0.dldVnodeis 0x16fc1180, vnode is 0x16f09930
2018.11.6 18:14:2 777827.VifFsdLookupHook dldVnode is 0x16fc1180, vnode:0x16f09930,dldvnode type:0, filename:/Volumes/mac/Users/mac/wst/share/test1234.txt, procname:nano
2018.11.6 18:14:2 777840.VifFsdLookupHook This is the old vnode,0x16f09930
2018.11.6 18:14:2 777842.VifReplaceVnodeByCovering dldVnode type is 0.dldVnodeis 0x16fc1180, vnode is 0x16f09930
2018.11.6 18:14:2 777850.VifFsdGetattrHook vnode:0x16f09930.
2018.11.6 18:14:2 779861.Enter the function of VnodeAuthorizeCallback, vnode = 0x16f09930.filename:test1234.txt
2018.11.6 18:14:2 779864.FltHookVnodeVop return 3, vnode=0x16f09930.
2018.11.6 18:14:2 780788.VifFsdGetattrHook vnode:0x16f09930.
**2018.11.6 18:14:2 780801.VifFsdReadHook filename:test1234.txt  procname:nano oriVnode:0x16f09930, vnode:0x16f09930.**
2018.11.6 18:14:2 781394.VifFsdReadHook filename:test1234.txt  procname:nano oriVnode:0x16f09930, vnode:0x16f09930.
2018.11.6 18:14:2 784393.VifFsdReadHook filename:test1234.txt  procname:nano oriVnode:0x16f09930, vnode:0x16f09930.
2018.11.6 18:14:2 785975.VifFsdReadHook filename:test1234.txt  procname:nano oriVnode:0x16f09930, vnode:0x16f09930.
2018.11.6 18:14:2 787401.VifFsdReadHook filename:test1234.txt  procname:nano oriVnode:0x16f09930, vnode:0x16f09930.

I think I'd better try to replace the vnode to check the problem can be resolved.

**Comment by wangsongtaoliuli** [comment]
Although the vfs_vget was called , but I found the process is Finder not nano. It means nano did not get the original vnode from vfs_vget function. 
The problem is still exist. And I think the problem is not caused by name_cache. I have checked LookupHook before return, the vpp has been replaced.
2018.11.7 10:31:23 434660.VifFsdLookupHook filename:/Volumes/mac/Users/mac/wst/share/testxxxxxxxx.txt  procname:nano .
2018.11.7 10:31:23 434707.VifFsdLookupHook This is the old vnode,0x28cf82e8
2018.11.7 10:31:23 434710.VifReplaceVnodeByCovering dldVnode type is 0.dldVnodeis 0x2a987a00, vnode is 0x28cf82e8
2018.11.7 10:31:23 434717.Coverd branch VifFsdReclaimHook the vnode:0x28caa838
2018.11.7 10:31:23 434721.Coverd branch VifFsdReclaimHook the vnode:0x28caa838
2018.11.7 10:31:23 434723.RemoveIOVnodeByBSDVnode the vnode:0x28caa838 dldvnode:0x0.
2018.11.7 10:31:23 434726. Coverd branch VifFsdReclaimHook the vnode:0x28caa838
2018.11.7 10:31:23 434734.VifVnodeHashTable::CreateAndAddIOVnodByBSDVnode, the ioVnodeNew:0x2d169a80, vnode: 0x28caa838, dldVnodeType:1.
2018.11.7 10:31:23 434737.FltHookVnodeVop return 3, vnode=0x28caa838.
2018.11.7 10:31:23 434739.lVifReplaceVnodeByCovering, dldVnodeType:1 ,dldCoveringVnode:0x2d169a80, vnode is 0x28caa838.
2018.11.7 10:31:23 434743.VifFsdGetattrHook vnode:0x28cf82e8.
2018.11.7 10:31:23 434749.VifFsdLookupHook This is the new vnode,0x28caa838
2018.11.7 10:31:23 434751.The lookup returned vnode is 0x28caa838, fsnode is 0x0, bReplaceVnode is 1.

**Comment by slavaim** [comment]
After loading the filter kext try to unmount and then mount again the shared directory in /Volumes . If this doesn't help try to call cache_purge() in VnodeAuthorizeCallback() for VDIR == vnode_vtype(vnode). If anything of this helps the problem is with the name cache.

**Comment by wangsongtaoliuli** [comment]
Thank you for your replay,
I found when read from shared directory,  the value of variable  mount::mnt_compound_ops is 1,   after calling VNOP_LOOKUP,  kernel update the vnode by call VNOP_COMPOUND_OPEN. But the VNOP_COMPOUND_OPEN is private in kernel source. We have change the mount::mnt_compound_ops  to zero, and the problem resolved. Do you have some good solution for this kind of problem?

I found another problem,  when I save the modified txt document use process textEdit， always remain an empty directory like 8888.txt.sb-95c19df4-hXbdC2.  when edit the txt document, TextEdit will create a file named 8888.txt.sb-95c19df4-hXbdC2/8888.txt, and write this file, after writing, TextEdit will rename this file to original file. Without the covering vnode, the directory will be removed after rename.But with the covering vnode, the directory remained. 
 when create the covering vnode, we use the original vnode's dvp as the covering vnode's parent, when process rename hook, shall we remove the relationship between the dvp and the covering vnode? I guess the remaining directory still has relation to the covering vnode.

Best regards

**Comment by slavaim** [comment]
Regarding the first part. 

The ```vnop_compound_open_desc``` is still exported by the kernel

```
slavas-MacBook-Pro:home slava$ nm /System/Library/Kernels/kernel | grep vnop_compound_open_desc
ffffff8000a632d0 D _vnop_compound_open_desc
```

But it is not exported by ```BSDKernel.kext``` which is linked as ```com.apple.kpi.bsd```
```
slavas-MacBook-Pro:PlugIns slava$ nm /System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext/BSDKernel | grep vnop_compound_open_desc
slavas-MacBook-Pro:PlugIns slava$ nm /System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext/BSDKernel | grep vnop_pageout_desc
                 U _vnop_pageout_desc
```
A workaround is to create your own "MyCompanyBSDKernel.kext" using an example 
 from this repository https://github.com/slavaim/dl_kextsymboltool and load it as a dependency for your main kext. Don't forget to add a dependency to your main kext's ```Info.plist``` like you did for ```com.apple.kpi.bsd```.
```
$sudo kextload -d /path/to/my/kext/MyCompanyBSDKernel.kext /path/to/my/kext/MyCompanyMain.kext 
```

You need to reexport ```_vnop_compound_open_desc``` with MyCompanyBSDKernel.kext
```
 #!/bin/bash
 NAME=/work/MyCompanyBSDKernel  
 # old MacOS X placed the kernel in the root directory
 # nm -gj /mach_kernel > allsymbols  
 # on the lates macOS the kernel can be found at /System/Library/Kernels
 nm -gj /System/Library/Kernels/kernel > allsymbols 
 echo "_vnop_compound_open_desc" > ${NAME}.exports  
 # include any more symbols needed    
 
 dl_kextsymboltool -arch i386 -import allsymbols  -export ${NAME}.exports -output ${NAME}_32  
 dl_kextsymboltool -arch x86_64 -import allsymbols -export ${NAME}.exports -output ${NAME}_64 
 
 # make a universal kext 
 lipo -create ${NAME}_32 ${NAME}_64 -output ${NAME} 
```

As you will have two kexts a user should allow the both with the System Preferences->Security and Privacy pan. There is a bug in macOS - the second time you open this panel using a popup up dialog shown by the system it might not show a kext name and a button to allow it (the area is blank). You need to open this dialog through System Preferences->Security and Privacy then a kext name and the allow button are shown.

You also declare it somewhere like
```
extern struct vnodeop_desc  vnop_compound_open_desc;
```

Then you need to hook compound_open in vnode opertions by adding a new entry to ```gVifVnodeVopHookEntries```  
```
{ &vnop_compound_open_desc,        (VOPFUNC)VifFsdCompoundOpenHook },
```

a new entry for ```gVifVnodeVopEnumEntries```  
```
   { &vnop_compound_open_desc,        (VOPFUNC)FltVopEnum_compound_open  },
```

and implement a hook similar to ```VifFsdLookupHook```  
```
static int
VifFsdCompoundOpenHook(struct vnop_compound_open_args *ap)
{
 /*here like in VifFsdLookupHook*/
 ....
    int (*orig)(struct vnop_compound_open_args *ap);
    
    orig = (int (*)(struct vnop_compound_open_args*))VifGetOriginalVnodeOp( ap->a_dvp, FltVopEnum_compound_open );
    assert( orig );
 ....
 /*here like in VifFsdLookupHook*/
}
```

**Comment by wangsongtaoliuli** [comment]
Thank you for your reply.  I use the script above, and create an empty ioKit kext. Replace the binary file generated by the tool. I have revised all you suggested. But when I load the kext, some error occurred. 

sdeMac-3:testFilter s$ sudo kextutil -d specFilter.kext Filter.kext
Rejecting invalid/inauthentic kext for bundle id com.esafenet.specFilter at location specFilter.kext/ -- file:///Users/s/testFilter/.
Filter.kext - no compatible dependency found for com.esafenet.specFilter.
Rejecting invalid/inauthentic kext for bundle id com.esafenet.specFilter at location specFilter.kext/ -- file:///Users/s/testFilter/.
Filter.kext - no compatible dependency found for com.esafenet.specFilter.
Rejecting invalid/inauthentic kext for bundle id com.esafenet.specFilter at location specFilter.kext/ -- file:///Users/s/testFilter/.
Filter.kext - no compatible dependency found for com.esafenet.specFilter.
Diagnostics for Filter.kext:
Dependency Resolution Failures: 
    Only incompatible kexts found for these libraries: 
        com.esafenet.specFilter

**Comment by wangsongtaoliuli** [comment]
I use the script above, and create an empty ioKit kext. Replace the binary file generated by the tool. But Kextutil failed when loading my driver on IMac 10.13.3. You're appreciated if you tell me something about that! Thanks. 
sdeMac-3:testFilter s$ sudo kextutil -d specFilter.kext Filter.kext
Rejecting invalid/inauthentic kext for bundle id com.wangsongtao.specFilter at location specFilter.kext/ -- file:///Users/s/testFilter/.
Filter.kext - no compatible dependency found for specFilter.
Rejecting invalid/inauthentic kext for bundle id com.wangsongtao.specFilter at location specFilter.kext/ -- file:///Users/s/testFilter/.
Filter.kext - no compatible dependency found for specFilter.
Rejecting invalid/inauthentic kext for bundle id com.wangsongtao.specFilter at location specFilter.kext/ -- file:///Users/s/testFilter/.
Filter.kext - no compatible dependency found for com.wangsongtao.specFilter.
Diagnostics for Filter.kext:
Dependency Resolution Failures: 
    Only incompatible kexts found for these libraries: 
        com.wangsongtao.specFilter

**Comment by wangsongtaoliuli** [comment]
I have resolved the problem. It is because of the Info.plist file. I am so grateful for your help.

**Comment by slavaim** [comment]
Hi,
Anyway, I would recommend to get rid of a dependency and use a method form here https://github.com/jzdziarski/kernelresolver  to resolve kernel exports instead of specFilter.kext . This method is not perfect as it uses an undocumented unslided base address for the kernel but it works on all latest kernels.
